GET http://127.0.0.1:8000/api/people/
Content-Type: application/json

{
    "name": "Django Rest",
    "age": 30
}

POST http://127.0.0.1:8000/api/people/
Content-Type: application/json

{
    "name": "Django",
    "age": 30
}
